### ISSUE TITLE
 Deliver Message Schema In-Band

### ISSUE THREAD

**Issue by adkapur** [FIXTradingCommunity/fixp-specification#25]
Need to explore the feasibility of exchanging the SBE schema inline within the context of a FIXP session, not sure if this could be accomplished through FIXP messaging or application layer.

Currently no mechanism defined in FIXP or application layer to do this.

Closest possibilities appear to be XMLnonFIX message (35=n) in FIXT or the MsgTypGrp component block in FIXT logon message (35=A)

This is little bit of a chicken and egg situation since the SBE schema will have to be provided out of band for the first time or delivered via existing FIX ASCII encoding as a 35=n message and then future versions could also be publicised as such

**Comment by donmendelson** [comment]
I proposed such a feature some time ago. The working group wanted to generalize in-band template delivery to cover all FIX encodings, not just SBE. FIXP session layer is supposed to work with any presentation later. Let's keep this ticket open. Proposals are welcome.

**Comment by adkapur** [comment]
Let us introduce a new FIXP message to support dissemination of encoding information in-band once a FIXP session has been established. This would be something similar to the XMLnonFIX message.

**Comment by donmendelson** [comment]
Requirements to consider:

- The feature should work for any FIX encoding that has templates, including SBE, GPB and FIXML schemas.
- The new message must identify the encoding of the template. We can borrow registered values of encodings from [Simple Open Framing Header](https://github.com/FIXTradingCommunity/fix-simple-open-framing-header).
- An encoding may require more information, such as versioning or format of the template if more than one form is supported. For example, a template may be supplied in source form, such as a .proto file for GPB, or in a binary format.
- The message may be sent in either a point-to-point or multicast session.

**Comment by donmendelson** [comment]
Another thought about requirements: it would be useful to optionally provide an effective date-time for a new template. For example, today we are using message schema version 3, but as of next Monday, we will use version 4, provided

**Comment by kleihan** [comment]
I think this effectiveness is a valuable addition. It should be able to be expressed in two different ways:
absolute: effective date-time
relative: effective application version
Is the assumption that there can be more than one schema version per application version?

**Comment by adkapur** [comment]
We have also shopped this around and the initial feedback is that something like this (effective date & time) would be an excellent validation feature
