### ISSUE TITLE
Clarify multicast as single Topic or multiplexed flow

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fixp-specification#3]
Multicast Session Protocol section 5 is vague about Sequence or Context messages for sequencing. It would seem to be parallel to simplex versus multiplexed point-to-point sessions. If only a single Topic is published, then Sequence can be used since there is no context switch. If multiple topics are published on a shared multicast transport, then Context must be used.

**Comment by afuruhed** [comment]
I agree. The XMIT spec says so in a general way in the "Multiplexing Recoverable Flows" section without making a difference between point-to-point and one-to-many. The same applies to both types.
