### ISSUE TITLE
[04PointToPointSessionProtocol.md] NextExpectedSeqNum support

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#36]
> 04PointToPointSessionProtocol.md
> The server should evaluate NextSeqNo to determine whether it missed any messages after re-establishment of a recoverable flow. If so, it may immediately send a RetransmitRequest after sending EstablishAck.

Why do not send NextExpectedSeqNum in Establishment and EstablishmentAck messages and send missed messages automatically?

**Comment by donmendelson** [comment]
Establishment must be completed successfully before transmission or retransmission of application messages. Sending NextExpectedSeqNum in Establish is a slight optimization to allow detection of a gap without waiting for a Sequence message. Retransmission is never sent automatically without a request from the peer. It is an iterative process to prevent blocking of real-time messages with a form of flow control.

**Comment by donmendelson** [comment]
This wording should be changed. The server could send EstablishmentAck then Retransmission and the first batch of retransmitted application messages. Retransmission is an iterative process to affect flow control and prevent blocking of real-time  messages.
