### ISSUE TITLE
[04PointToPointSessionProtocol.md] Usecase for RequestTimestamp?

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#37]
Could you please explain how should RequestTimestamp be used? What is the use case for this field?

**Comment by ujos** [comment]
Is it correct that RequestTimestamp should be treated as RequestID and should be unique?

**Comment by donmendelson** [comment]
Correct. The RequestTimestamp is just used as a unique ID to prevent matching a response to a stale request. (There is no need for clock synchronization for this purpose.)
