### ISSUE TITLE
[04PointToPointSessionProtocol.md] Initiator and acceptor in "Terminate Response"

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#38]
> Upon receiving a Terminate message, the acceptor must respond to the initiator with a Terminate message before disconnecting the transport.

While being reading that, I was sure acceptor is a Server side. 
I guess it worth to clarify "initiator of terminate" and "acceptor of the terminate request".

**Comment by donmendelson** [comment]
Best to avoid acceptor and initiator terms that had specific meanings in FIX4 and FIXT, while FIXP uses client and server. 
If either party can take action, say peer instead of counterparty when referring to a communications partner (counterparty is a trading relationship).
