### ISSUE TITLE
Multicast session lacks keepalive interval

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fixp-specification#4]
A multicast publisher sends heartbeats at regular intervals when idle, as for a point-to-point session.

> During the lifetime of a multicast session, its publisher should send Sequence or Context messages as a heartbeat at regular intervals when the session is otherwise inactive. This allows a receiver to tell whether a session is live and has not reached the end of its logical flow.

The problem is that the interval is not communicated to a consumer. There is no way for it to know when the interval is exceeded.

KeepaliveInterval could be added to the Topic message to serve the same purpose it does in Establish, to tell the expected interval.

**Comment by afuruhed** [comment]
Agreed, I will go back and do that in XMIT (add KeepaliveInterval to Topic).

**Comment by donmendelson** [comment]
Agreed in principle on 3/21/2016
