### ISSUE TITLE
[04PointToPointSessionProtocol.md] 'Sequence is too low' case is not explained

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#40]
In the FIXT specification stated:

> Whenever possible it is recommended that FIX engine attempt to send a Logout message with a text message of “MsgSeqNum too low, expecting X but received Y”

Does FIXP specification cover this case?

**Comment by donmendelson** [comment]
For a sequence number that has already been received, the description of Idempotent flow states:

>  If a transaction has already been applied, a duplicate request should be silently dropped.

**Comment by ujos** [comment]
In FIXT "SeqNum too low" case meant that someone tried to establish connection from another application. 

As far as each session in FIXP is identified by unique identifier which is generated randomly, that is not a issue anymore.

Thanks
