### ISSUE TITLE
[04PointToPointSessionProtocol.md] Why RestransmitRequest.SessionId field is required?

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#41]
According to specification, field SessionId in the RestransmitRequest message is required. I guess it should be  required only if transport is shared between several sessions.

**Comment by donmendelson** [comment]
As the spec is currently written, SessionId is required in RetransmitRequest. 

Not normative: the working group has had discussions about out-of-band recovery. This would require identification of the original session for which recovery is requested.
