### ISSUE TITLE
[06SummaryOfSessionMessages.md] Protocol Violations: Session level messages before session is Established

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#57]
I have few questions regarding subj:
- How should FIXP Acceptor handle any Session Level message message while processing Negotiate message?
- How should FIXP Acceptor handle any Session Level message message while processing Establish message?

**Comment by donmendelson** [comment]
The spec is not explicit about when heartbeating should begin. In my view, no application messages or other session messages should be exchanged until EstablishAck is sent. Any intervening messages would be a protocol violation.

We should create a new section in the spec to summarize all protocol violations, as was done in the SBE spec.

**Comment by ujos** [comment]
Just a remark. Sending any data to remote peer while it is not authorized can be harmful. Sent data can be used attacker later.

**Comment by donmendelson** [comment]
Correction to my earlier comment. There already is a summary of protocol violations in section 6, but make sure it is comprehensive.

**Comment by adkapur** [comment]
If any message is sent whether business or session before session is established then it will be terminated period
