### ISSUE TITLE
[04PointToPointSessionProtocol.md] Terminate Response should be revised

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#58]
> On a point-to-point session, either peer may initiate termination. Upon receiving a Terminate message, the acceptor must respond to the initiator with a Terminate message **before disconnecting the transport**.

I believe this sentence should be revised. Currently it means that Acceptor must send Terminate if he is going to close socket. If Acceptor does not want to close socket, he should not send Terminate.

**Comment by donmendelson** [comment]
There is currently no provision in the spec for refusing to terminate. What would be the use case for that?

**Comment by ujos** [comment]
I did not mean that Acceptor wants to refuse Termination. I just would like to make text more clear. i.e :

"Upon receiving a Terminate message, the acceptor must respond to the initiator with a Terminate message then close the transport."

**Comment by adkapur** [comment]
Acceptor has to close the transport only when initiator sends the "socket connection reset by peer" (after receiving the Terminate Response) and not when the Terminate response is sent by Acceptor
