### ISSUE TITLE
Add FIXP messages to FIX Repository

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fixp-specification#6]
To populate FIXP messages in FIXimate and other reference tools, add FIXP message IDs and field tags to the FIX Repository.

**Comment by donmendelson** [comment]
Current version of the FIX Repository is 2010 Edition. See http://www.fixtradingcommunity.org/pg/file/fplpo/read/30263/fix-repository-2010-edition

**Comment by adkapur** [comment]
Just out of curiosity has this been done? FIXP messages do not seem to be visible in FIXimate.

**Comment by donmendelson** [comment]
It has been approved by the GTC but not yet published.

**Comment by adkapur** [comment]
Okay got it and also saw it here at --> https://github.com/FIXTradingCommunity/fixp-specification/blob/master/v1-0-RC3/resources/FixRepositoryForFIXP.xml

Will the msgType="XX" and field id's be assigned real values or will they be displayed in FIXimate as-is?

> <message`

 added="FIXP1.0RC3"  id="1" name="Negotiate" msgType="XX" category="Session" section="Session" >
<fieldRef added="FIXP1.0RC3" id="1" name="SessionId" required="1" 

> />

Also are required fields in the repository defined as required=1 and optional as required=0?

**Comment by donmendelson** [comment]
Yes, new message types and field IDs are assigned as part of the FIX Repository build process.

In the current 2010 Edition, attribute "required" is binary 0 or 1. In the upcoming 2016 edition, attribute "presence" had several possible values.

**Comment by donmendelson** [comment]
I enquired about this. It will be bumped up in priority.

I am travelling this week so I made not respond to messages quickly.

Don
