### ISSUE TITLE
Is "Finished Receiving message without Finished Sending" protocol violation?

### ISSUE THREAD

**Issue by ujos** [FIXTradingCommunity/fixp-specification#61]
What if remote peer sends Finished Receiving message while local peer did not send Finished Sending message. Is this Protocol Violation case?

**Comment by donmendelson** [comment]
I think yes. This should be added to a list of protocol violations.

**Comment by adkapur** [comment]
Yes generally speaking any thing received out of sequence will be terminated such as sending FinishedReceiving before FinishedSending, sending Terminate after FinsihedSending but before FinishedReceiving etc

**Comment by ujos** [comment]
>  sending Terminate after FinsihedSending but before FinishedReceiving etc

Why Terminate before FinishedReceiving is a protocol violation?

**Comment by donmendelson** [comment]
@ujos , an edge case: if the peer sent FinishedSending but then violated the protocol by sending another application message, it seems you would be obligated to terminate immediately. But that might be counter to your best interests if you had other messages queued up before responding with FinishedReceiving. A bit of a mess.  Bad behavior should have consequences.

**Comment by ujos** [comment]
I'm not sure if I understand the case. 
* If initiator of Finalization sends Terminate before receiving FinishedReceiving - it is OK. It requires to close connection for some reason. 
* If acceptor of Finalization sends Terminate before sending FinishedReceiving - it is also OK as Terminate message can be sent in parallel to sending FInishedSending.
