### ISSUE TITLE
Any advice to start a SBE/FIXP client program

### ISSUE THREAD

**Issue by chengm349** [FIXTradingCommunity/fixp-specification#77]
I have a question raised in https://stackoverflow.com/questions/68434287/fix-performance-session-layer-fixp-and-sbe
Wondering whether you people can give some suggestion.

**Comment by kleihan** [comment]
Please use the FIX discussion forum (https://forum.fixtrading.org) for such questions. There was a recent question that may be related: https://forum.fixtrading.org/t/fix-sbe-with-simple-open-framing-header-on-top-of-a-fix-performance-session/16012. 

There is also a demonstration project Conga in GitHub (https://github.com/FIXTradingCommunity/conga) that should provide some suggestions. Could you share which exchange you are trying to access with SBE/FIXP?

**Comment by donmendelson** [comment]
Project Conga demonstrates FIXP over WebSocket protocol. For a project that demonstrates SBE+FIXP over TCP or UDP, see project [silverflash](https://github.com/FIXTradingCommunity/silverflash). Both projects are Java and open source.  Silverflash demonstrates every combination of FIXP flow type; you only need to implement the ones supported by your exchange. Both FIXTradingCommunity projects use SBE encoder/decoder generation from project [simple-binary-encoding](https://github.com/real-logic/simple-binary-encoding). That project can generate C++ code among other languages.

I would not recommend attempting to modify an existing FIX engine for this purpose. The high performance protocols SBE and FIXP were designed for low latency and to avoid the inefficiencies and ambiguities of "FIX classic" protocols.

**Comment by chengm349** [comment]
Hi Don Hanno,

Your replies are very helpful and helped me to understand the picture much faster. I raises a topic 16045<https://forum.fixtrading.org/t/silverflash-reference-for-c-client-application/16045>. Hope to have your further guide.

Warm Regards.
Ming

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
